### ISSUE TITLE
Allow disabling https certificate validation

### ISSUE THREAD

**Issue by codygman** [bos/wreq#102]
Can be done in http-client with the following:

```newManager $ mkManagerSettings (def { settingDisableCertificateValidation = True }) Nothing >>= \manager -> withResponse "https://insecure" manager $ \res -> print $ responseStatus res```

I think you'd need to internally use mkManagerSettings from [Network.HTTP.Client.TLS](https://hackage.haskell.org/package/http-client-tls-0.3.4.2/docs/Network-HTTP-Client-TLS.html).

**Comment by ondrap** [comment]
This seems to be a settings of `Manager`; you can change the `Manager` settings in `wreq` (see e.g. the `getWith` function that uses the `Options` parameter). So I think this is supported. If you disagree, write here/reopen.
