### ISSUE TITLE
partDir - application/x-directory

### ISSUE THREAD

**Issue by apeyroux** [bos/wreq#105]
Hello, 

I use `partFile` to **POST** a file but I would like to use a kind of `partDir` to **POST** a **application/x-directory**. I found nothing in the doc or code. Maybe I missed something?

Regards

**Comment by ondrap** [comment]
It seems that application/x-directory is not a standard. I'm closing the issue, if you find some more information, feel free to reopen, but it seems to me wreq should support mainly things working according to some standards/rfcs etc.
