### ISSUE TITLE
Failure to build tests on stackage

### ISSUE THREAD

**Issue by mihaimaruseac** [bos/wreq#107]
```haskell
Building test suite 'doctest' for wreq-0.5.1.0..
[1 of 1] Compiling Main             ( tests/DocTests.hs, dist/build/doctest/doctest-tmp/Main.o )

tests/DocTests.hs:6:1: error:
    Could not find module ‘Build_doctest’
    Use -v to see a list of the files searched for.
  |
6 | import Build_doctest (deps)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ondrap** [comment]
I kind of tried to look at this and I don't quite comprehend it. I assume `Build_doctest` is some kind of virtual module with some constants regarding build process; how does this look in GHC-8.2? I cannot find documentation anywhere... help would be appreciated.

**Comment by ondrap** [comment]
This should hopefully be fixed now.

**Comment by mihaimaruseac** [comment]
That is correct, tests are fixed. Thanks
