### ISSUE TITLE
Can I access request body (before sending) or http Manager? 

### ISSUE THREAD

**Issue by ruiheng** [bos/wreq#117]
In a project, I use `wreq` to access some remote web APIs. According to doc, I use functions in `Network.Wreq.Session`. I was happy with that. Until I found that some APIs required a custom header that must know the request body length. I don't know how to do it.

My current workaround is to switch to http-client functions temporarily: patch wreq source to allow me to access http manager (`seshManager`), so that I can use http-client functions with the manager, and http-client functions allow me to get request body bytes (by inspecting constructors of `RequestBody`).

What's the correct way to accomplish this?

Thanks for your help.

**Comment by ondrap** [comment]
The body must be `Postable`; the `Postable` interface exposes the function `postPayload :: a -> Request -> IO Request`; so create some empty `Request`, run the `postPayload`, extract `requestBody` from the resulting request and work on that.

**Comment by ruiheng** [comment]
That works great. Thanks a lot.
