### ISSUE TITLE
Can't install 0.5.2.0

### ISSUE THREAD

**Issue by anacrolix** [bos/wreq#118]
```
$ cabal install wreq
Resolving dependencies...
Downloading wreq-0.5.2.0...
Invalid package wreq-0.5.2.0
```
0.5.1.0 does work tho:
```
$ cabal install wreq==0.5.1.0
Resolving dependencies...
Downloading wreq-0.5.1.0...
Configuring wreq-0.5.1.0...
Building wreq-0.5.1.0...
Installed wreq-0.5.1.0
```

**Comment by ondrap** [comment]
Honestly I have no idea. Could you try to find out where is the problem? It's part of stackage, it compiles on the newer ghc in hackage, it seems some problem with your setup - possibly some old version of cabal/ghc?
