### ISSUE TITLE
Network.Wreq.Internal.AWS should normalise the path in canonicalString according to the spec

### ISSUE THREAD

**Issue by justinpastoncooper** [bos/wreq#123]
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html says, "Normalize URI paths according to RFC 3986. Remove redundant and relative path components. Each path segment must be URI-encoded."

`Network.Wreq.Internal.AWS` does not currently do this itself, and when it is called implicitly by using `postWith` and a path which contains non-alpha-numeric characters, the path is included verbatim without URL-encoding in the canonical string, which causes a signing exception on the server.

I'm not quite sure whether this is the responsibility of `Network.Wreq.Internal.AWS`, or whether the path in the `Request` is meant to be properly encoded already, but I managed to fix this issue by, in `AWS.hs`, in the definition of `canonicalReq`, replacing `req ^. path` with `S.intercalate "/" $ map (urlEncode False) $ S.split '/' (req ^. path)`. This doesn't perform full normalisation, but fixes it for my case. Is this the right way to go about things, and if so, shall I make a pull request?

**Comment by justinpastoncooper** [comment]
Example:

The path `/elastic-search-index-*` should be provided to the canonical string as `/elastic-search-index-%2A`.

**Comment by justinpastoncooper** [comment]
Note: paths are not meant to be normalised for requests to S3.

**Comment by ondrap** [comment]
Honestly, I have no idea. I'm using `amazonka-s3` package to acces the S3 (and other amazonka packages). Do I understand correctly that this is  a problem with the signing algorithm?

**Comment by justinpastoncooper** [comment]
@ondrap Yes, there is a problem with the signing algorithm. S3 should indeed work, as the path components are not meant to be normalised anyway. For other services, paths which are already normalised, like alpha-numeric paths, will work fine. It's only when it comes to "special" characters like `*`.

**Comment by ondrap** [comment]
If you make a PR, I'll happily merge it.

**Comment by justinpastoncooper** [comment]
@ondrap Can you take a look at this and the other PR?
