### ISSUE TITLE
oauth2Token adding new line character to a BS.readFile and problem with github api with auth

### ISSUE THREAD

**Issue by teuffy** [bos/wreq#126]
- Context:

Wreq within Ihaskell + Ipython 

- issue:

`echo "1234" > .github-api-token` 
`BS.readFile ".github-api-token" -- 1234`
`oauth2Token <$> BS.readFile ".github-api-token" -- OAuth2Token "1234\n"`

`githubAuth <- oauth2Token <$> BS.readFile ".github-api-token" --  OAuth2Token "1234\n"`

As Github is not responding to queries with
`opts = defaults & auth ?~ githubAuth` 
as I guess that the new line character is not accepted by github

But Github is responding with
`opts = defaults & auth ?~oauth2Token "1234"`

Any idea what I am doing wrong or is it an issue?

**Comment by ondrap** [comment]
I don't quite understand the question. The token obviously shouldn't include newline. As you have found out. So... you are sending the newline, which is wrong. Strip it and it should work. Feel free to reopen if you feel there is something wrong with wreq, but this seems like a problem in your code ;) (which you have nicely diagnosed).

**Comment by teuffy** [comment]
It is the oauth2Token seems that seems to be adding the \n

**Comment by teuffy** [comment]
Sorry but where I am confused is when I do
`Data.ByteString.readFile "/tmp/token"`
I got within Jupyter notebook 
`1234`
with same file as yours
co@co-mbp3 IHaskell3  >λ> od -c /tmp/token
0000000    1   2   3   4  \n                                            
0000005

**Comment by ondrap** [comment]
Jupyter has probably some special logic for printing strings. Try:

```
show <$> Data.ByteString.readFile "/tmp/token"
```

**Comment by teuffy** [comment]
Many thanks Ondrej for your guidance.
Here the workaround that I am using

`import Network.Wreq`
`import qualified Data.ByteString as BS`
`noNline = BS.filter (/= BS.head "\n") `
`githubAuth <- oauth2Token . noNline <$> BS.readFile "/tmp/token"`
