### ISSUE TITLE
#126 reopen

### ISSUE THREAD

**Issue by teuffy** [bos/wreq#127]
It seems related to #122 bit not sure
oauth2Token adds \n to the ByteString result.

**Comment by ondrap** [comment]
No, it does not. See my last comment in #126. Also, if you cared to have a look at the source code, it looks like this ( https://hackage.haskell.org/package/wreq-0.5.2.1/docs/src/Network-Wreq.html#oauth2Token )

```
oauth2Token :: S.ByteString -> Auth
oauth2Token = OAuth2Token
```
