### ISSUE TITLE
Won't build against time-1.5

### ISSUE THREAD

**Issue by artemshitov** [bos/wreq#43]
Seems like `time` dropped its dependency on `old-locale` in 1.5.

```
Network/Wreq/Internal/AWS.hs:130:42:
    Couldn't match expected type ‘time-1.5:Data.Time.Format.Locale.TimeLocale’
                with actual type ‘System.Locale.TimeLocale’
    NB: ‘time-1.5:Data.Time.Format.Locale.TimeLocale’
          is defined in ‘Data.Time.Format.Locale’ in package ‘time-1.5’
        ‘System.Locale.TimeLocale’
          is defined in ‘System.Locale’ in package ‘old-locale-1.0.0.6’
    In the first argument of ‘formatTime’, namely ‘defaultTimeLocale’
    In the first argument of ‘(.)’, namely
      ‘formatTime defaultTimeLocale "%Y%m%dT%H%M%SZ"’
```

**Comment by markus1189** [comment]
Any plans on fixing the current `wreq` and uploading a new version to hackage?  WIth ghc-7.10 `time-1.5.0.0` is installed so wreq does not build at all

**Comment by seagreen** [comment]
Hopefully this isn't being annoying -- I'm also interested in when the new version of `wreq

**Comment by seagreen** [comment]
Hopefully this isn't being annoying -- I'm also interested in when the new version of wreq will be uploaded to Hackage.

One point in favor of a quick upload is that there isn't a version bound on `time` right now in the .cabal file. This means the issue with `time` is found at compile time, not at dependency resolution.
