### ISSUE TITLE
Compiling on FPComplete

### ISSUE THREAD

**Issue by arnoblalam** [bos/wreq#44]
Hi:

Is there a way to get Wreq to compile on FPComplete.  I have tried adding it to the extra packages, but seem to be caught in dependency hell (FPComplete seems to provide incompatible versions of http-client and lens library, and no PSQueue library).

Any way to get this to build on the FPComplete infrastructure?

**Comment by bos** [comment]
You'll need to ask the FP complete people. This isn't the right place to ask for help with their platform.

**Comment by Fresheyeball** [comment]
@bos did you every get this figured out? I'm facing the same problem.

**Comment by bos** [comment]
Folks, I don't use or support Stackage. Please send your support requests to @snoyberg or someone else who can actually help.
