### ISSUE TITLE
delete and deleteWith requestBodies

### ISSUE THREAD

**Issue by arnoblalam** [bos/wreq#46]
Hi:

I am trying to implement an API for the IronMQ message queueing service.  Their delete method requires that the body of the DELETE request have some sort of JSON

http://dev.iron.io/mq/reference/api/#delete_a_message_from_a_queue

It does not look like Wreq allows delete and deleteWith methods to incorporate a body into the request. Is this a feature that can be added?

**Comment by tanmaig** [comment]
As a related query, I would like to set a request body to the customMethodWith function. Any way of adding that?

**Comment by bos** [comment]
Please see #76.
