### ISSUE TITLE
Add FormParam instances for Putable

### ISSUE THREAD

**Issue by bbangert** [bos/wreq#49]
In many cases PUT is relatively identical in usage to POST. As such, it'd be handy if Putable honored the same instances as Postable including the setting of the Content-Type to a form-encoded when using [FormParam].

I had to copy/edit the Postable instances, which works fine but it feels like this should be in wreq:
https://github.com/bbangert/push-tester/blob/master/spTester/SimpleTest/Types.hs#L38

**Comment by owainlewis** [comment]
+1 this confused me a bit :)

**Comment by ondrap** [comment]
Is there any reason for separate Postable/Putable classes?
