### ISSUE TITLE
Missing ca-certificates

### ISSUE THREAD

**Issue by denibertovic** [bos/wreq#5]
When trying out `r <- get "http://httpbin.org/get"` from the tutorial on a Debian system with no ca-certificates package installed (meaning no /etc/ssl/certs directory) the command exits with an Exception "**\* Exception: /etc/ssl/certs/: getDirectoryContents: does not exist (No such file or directory)".

Seems we should handle this more gracefully (ie allow the user not to check certificates perhaps? in Python requests that verify=False I believe).

The other question is why was this triggered when the URL that's being accessed is http only?

Awesome work btw! :+1:

**Comment by noteed** [comment]
I don't know if this is related to this issue, but I was having

    getProtocolByName: does not exist (no such protocol name: tcp)

in a project of mine, and I solved it by `apt-get install netbase`, which provides `/etc/protocols`.

**Comment by tomfitzhenry** [comment]
I'm running Ubuntu 15.04's Docker image, and also ran into this problem. Installing Ubuntu's `netbase` package resolved this for me too.

**Comment by ondrap** [comment]
I'm closing this as it seems it's not quite wreq related.
