### ISSUE TITLE
Add `wreq` into stackage.

### ISSUE THREAD

**Issue by aloiscochard** [bos/wreq#52]
Hi @bos,

I would love to use `wreq` in a tool of mine which is part of stackage.
Are you interested into having `wreq` in stackage and being listed as maintainer?

(You basically just have to do a PR on that file: https://github.com/fpco/stackage/blob/master/build-constraints.yaml and add yourself with the package)

If not I can add it next to my packages for now.

Please let me know

Thanks!

**Comment by bos** [comment]
I'm not interested in stackage, but thank you for asking.

**Comment by aloiscochard** [comment]
I hope you won't mind me putting your package under my name.

I'll put a note, "maintained in behalf of ..." or something.

**Comment by bos** [comment]
That's fine by me.

**Comment by aloiscochard** [comment]
Great!

Thanks a lot.
