### ISSUE TITLE
AWS authentication fails when using S3 bucket via new domain name style

### ISSUE THREAD

**Issue by Dridus** [bos/wreq#55]
Posting to https://bucket.s3.amazonaws.com/object-name doesn't seem to work with Amazon returning an error: 

The provided 'x-amz-content-sha256' header must be a valid SHA256.

When I switch to https://s3.amazonaws.com/bucket/object-name it works correctly.

I suspect this is because `serviceAndRegion` in `Network/Wreq/Internal/AWS.hs` doesn't recognize this newer style of S3 service and so is sending a `x-amz-content-sha256` header, though I don't know why it would be bad to send one.

**Comment by ret** [comment]
Correct. I hadn't bothered handling the cname style way to ref s3 buckets, yet. Happy to take a peek and take a swing at it (will be a couple of weeks at least though, I fear). Feel free to share a pull request if you get to it and need a fix more quickly, please. If you do, please add a test to the AWS set to lock in the (valuable) addition.

**Comment by Dridus** [comment]
no rush from my end, I just changed to use the old path based syntax for now. if I have some free moments to rub together I will take a crack at a pull request as it shouldn't be that tricky to make `serviceAndRegion` do the right thing
