### ISSUE TITLE
Improve docs for Windows: specifically withSocketsDo

### ISSUE THREAD

**Issue by 3noch** [bos/wreq#56]
On Windows, the tutorial is disheartening when the first example fails with

```
*** Exception: FailedConnectionException2 "httpbin.org" 80 False getAddrInfo: does not exist (error 10093)
```

A Google search turns up [this solution](http://stackoverflow.com/questions/19159686/internalioexception-getaddrinfo-does-not-exist-error-10093-on-windows-8) which works. It would be very helpful if the tutorial mentioned it. Better yet, eliminate the need for it, but I know that's involved...

**Comment by 3noch** [comment]
I've noticed that directly using `pipes-http` does not require the use of `withSocketsDo` on Windows.

**Comment by bos** [comment]
It is no longer necessary to use `withSocketsDo` if you're using a modern version of the `network` package on Windows.
