### ISSUE TITLE
Mention concurrnecy issues, add manager/session helper

### ISSUE THREAD

**Issue by bbangert** [bos/wreq#57]
There's some performance and concurrency issues using wreq under heavy concurrent use. Several problems occur:
1. Creating a HTTP Client Manager is an expensive operation, the HTTP-Client docs recommend sharing one between requests (which shares the pools of TCP connections as well for efficient control of maximum TCP connections used)
2. Wreq's Session add's a CookieJar MVar, the use of this MVar means concurrent use of a wreq session does not make concurrent requests at once as the mvar remains locked for the duration of the request/response cycle
3. Wreq has no convenient way to create or use a session with an existing Manager (withSessionWith takes ManagerSettings, not an actual Manager, which means the expensive operation of making more Managers....)

I'm currently writing some of my own code to create a new session per thread, but using a shared Manager to confirm that this alleviates the concurrency issue and doesn't incur too much RAM overhead in the process. I can submit a PR with another helper function to use an existing Manager then.

**Comment by bbangert** [comment]
Seems I can't actually work-around this short of forking, because the Session constructors and record funcs are hidden, which means its impossible to use Wreq as-is properly in a concurrent environment efficiently.

**Comment by bbangert** [comment]
I made a branch with a 'withSessionManager' object, which works great with a Session per-thread, sharing the same Manager (only slightly more RAM usage than using a single Session).

Ideally there'd be a way to tell the Session I honestly don't care about retaining Cookie's, just make requests without retaining cookie's, as fast as possible, sharing the Manager connection pool. In that case, maybe the wreq Session would see there's no CookieJar, and run the request without it (and without the mvar lock).

**Comment by bos** [comment]
@bbangert, can you try the commit I just pushed and let me know if it helps?

**Comment by bbangert** [comment]
Sure, though it would be nice if there was a way to indicate I don't actually care about a CookieJar. If the Manager has a Nothing for a CookieJar it avoids the effort of sending cookies and parsing cookies received.

The patch here seems to allow for intermediary requests to have their cookies overwritten.

**Comment by etrepum** [comment]
I think it's too specialized to have the cookie jar tied to the HTTP manager at all. Consider a use case where you want to use as few TCP connections as possible but you're sending (interleaved!) requests on behalf of a handful of "agents".

**Comment by bbangert** [comment]
I agree with @etrepum, also, the underlying http-client lib lets you supply a None to avoid use of a cookie-jar entirely, it'd be nice to be able to do requests with no cookie-jar using wreq.

I forked and added a withManager that takes a http-client Manager to use (all threads get their own cookie-jar under mvar as it was), and the memory usage is fine.

**Comment by bbangert** [comment]
On a side-note, assuming it doesn't get two weird having the last request overwrite other data, shouldn't this use the strict version of atomicModifyIORef?

**Comment by ondrap** [comment]
I think this has been solved; most functions allow setting the manager directly through `Options` object. If you disagree, I can reopen.
