### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by animesh11** [bos/wreq#59]
In the documentation, this is mentioned

let opts = defaults & proxy .~ httpProxy "localhost" 8000
Which gives error
Prelude Network.Wreq Control.Lens Data.Aeson Data.Aeson.Lens> let opts = defaults & proxy .~ httpProxy "localhost" 8000

<interactive>:43:32:
    Couldn't match expected type ‘Maybe Proxy’ with actual type ‘Proxy’
    In the second argument of ‘(.~)’, namely
      ‘httpProxy "localhost" 8000’
    In the second argument of ‘(&)’, namely
      ‘proxy .~ httpProxy "localhost" 8000’

https://hackage.haskell.org/package/wreq-0.1.0.1/docs/Network-Wreq.html

Since proxy is "MayBe" type it should be
let opts = defaults & proxy .~ Just (httpProxy "localhost" 8000)

**Comment by jarandaf** [comment]
What version are you using? For latest one, this should work:

```haskell
let opts = defaults & proxy ?~ httpProxy "localhost" 8000
```

See [documentation](http://hackage.haskell.org/package/wreq-0.3.0.1/docs/Network-Wreq.html#v:proxy).

**Comment by jarandaf** [comment]
Although this typechecks, seems actually not to work (using an http proxy debug tool, `wreq`-triggered requests are not detected).
