### ISSUE TITLE
Build is failing on GHC 7.10.1

### ISSUE THREAD

**Issue by rnhmjoj** [bos/wreq#61]
Configuring wreq-0.3.0.1...
Building wreq-0.3.0.1...
Preprocessing library wreq-0.3.0.1...
[ 1 of 14] Compiling Network.Wreq.Lens.Machinery ( Network/Wreq/Lens/Machinery.hs, dist/build/Network/Wreq/Lens/Machinery.o )
[ 2 of 14] Compiling Paths_wreq       ( dist/build/autogen/Paths_wreq.hs, dist/build/Paths_wreq.o )
[ 3 of 14] Compiling Network.Wreq.Cache.Store ( Network/Wreq/Cache/Store.hs, dist/build/Network/Wreq/Cache/Store.o )
[ 4 of 14] Compiling Network.Wreq.Internal.Types ( Network/Wreq/Internal/Types.hs, dist/build/Network/Wreq/Internal/Types.o )

Network/Wreq/Internal/Types.hs:47:1: Warning:
    The import of ‘mconcat’ from module ‘Data.Monoid’ is redundant
[ 5 of 14] Compiling Network.Wreq.Internal.Lens ( Network/Wreq/Internal/Lens.hs, dist/build/Network/Wreq/Internal/Lens.o )
[ 6 of 14] Compiling Network.Wreq.Internal.AWS ( Network/Wreq/Internal/AWS.hs, dist/build/Network/Wreq/Internal/AWS.o )

Network/Wreq/Internal/AWS.hs:130:42:
    Couldn't match expected type ‘time-1.5.0.1:Data.Time.Format.Locale.TimeLocale’
                with actual type ‘System.Locale.TimeLocale’
    NB: ‘time-1.5.0.1:Data.Time.Format.Locale.TimeLocale’
          is defined in ‘Data.Time.Format.Locale’ in package ‘time-1.5.0.1’
        ‘System.Locale.TimeLocale’
          is defined in ‘System.Locale’ in package ‘old-locale-1.0.0.7’
    In the first argument of ‘formatTime’, namely ‘defaultTimeLocale’
    In the first argument of ‘(.)’, namely
      ‘formatTime defaultTimeLocale "%Y%m%dT%H%M%SZ"’
cabal: Error: some packages failed to install:
wreq-0.3.0.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by statusfailed** [comment]
The hackage version also fails for me, but the latest github version now seems to build fine.

**Comment by rnhmjoj** [comment]
So there is only need to upload a new version on hackage.

**Comment by ababkin** [comment]
also fails similarly on 7.8.3

**Comment by jcristovao** [comment]
Pinging @bos , any preview when version 0.4 will be in hackage?
Thanks

**Comment by fosskers** [comment]
A hackage update would nice, so I can update my libraries than depend on it.

**Comment by peti** [comment]
We have the same problem in NixOS: http://hydra.cryp.to/build/785343/nixlog/1/raw.

**Comment by fosskers** [comment]
Did @bos upload [this](http://hackage.haskell.org/package/wreq-sb)?

**Comment by deem0n** [comment]
Still can not install. here is my shelllog:
```
Preprocessing library wreq-0.3.0.1...
[ 1 of 14] Compiling Network.Wreq.Lens.Machinery ( Network/Wreq/Lens/Machinery.hs, dist/build/Network/Wreq/Lens/Machinery.o )
[ 2 of 14] Compiling Paths_wreq       ( dist/build/autogen/Paths_wreq.hs, dist/build/Paths_wreq.o )
[ 3 of 14] Compiling Network.Wreq.Cache.Store ( Network/Wreq/Cache/Store.hs, dist/build/Network/Wreq/Cache/Store.o )
[ 4 of 14] Compiling Network.Wreq.Internal.Types ( Network/Wreq/Internal/Types.hs, dist/build/Network/Wreq/Internal/Types.o )

Network/Wreq/Internal/Types.hs:47:1: Warning:
    The import of ‘mconcat’ from module ‘Data.Monoid’ is redundant
[ 5 of 14] Compiling Network.Wreq.Internal.Lens ( Network/Wreq/Internal/Lens.hs, dist/build/Network/Wreq/Internal/Lens.o )
ld: warning: directory not found for option '-L/private/tmp/ghc20150401-90656-rxy9sj/ghc-7.10.1/gmp-static'
[ 6 of 14] Compiling Network.Wreq.Internal.AWS ( Network/Wreq/Internal/AWS.hs, dist/build/Network/Wreq/Internal/AWS.o )

Network/Wreq/Internal/AWS.hs:130:42:
    Couldn't match expected type ‘time-1.5.0.1:Data.Time.Format.Locale.TimeLocale’
                with actual type ‘System.Locale.TimeLocale’
    NB: ‘time-1.5.0.1:Data.Time.Format.Locale.TimeLocale’
          is defined in ‘Data.Time.Format.Locale’ in package ‘time-1.5.0.1’
        ‘System.Locale.TimeLocale’
          is defined in ‘System.Locale’ in package ‘old-locale-1.0.0.7’
    In the first argument of ‘formatTime’, namely ‘defaultTimeLocale’
    In the first argument of ‘(.)’, namely
      ‘formatTime defaultTimeLocale "%Y%m%dT%H%M%SZ"’
cabal: Error: some packages failed to install:
wreq-0.3.0.1 failed during the building phase. The exception was:
ExitFailure 1

Dmitrij-Dorofeevs-MacBook-Pro:Books deem0n$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library 
Dmitrij-Dorofeevs-MacBook-Pro:Books deem0n$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.1

Dmitrij-Dorofeevs-MacBook-Pro:Books deem0n$ uname -a
Darwin dmitrijfeevsmbp 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
```

**Comment by iori-yja** [comment]
@deem0n use [wreq-sb](http://hackage.haskell.org/package/wreq-sb) instead.

**Comment by solatis** [comment]
What is this wreq-sb package you're talking about ? According to the hackage page it is maintained by @bos but it appears to just be a fork ?

**Comment by fosskers** [comment]
The actual maintainer is taking his sweet time uploading wreq 0.4 to
hackage. Someone got impatient, and so right now we're using wreq-sb.

**Comment by fosskers** [comment]
Thanks @bos!
