### ISSUE TITLE
Capturing response body for http exceptions

### ISSUE THREAD

**Issue by coco98** [bos/wreq#62]
How would I capture the response body for a URL that doesn't return a 2xx status, which is an ```HttpException```?
Say I want to capture the HTML of a url that returns 404. HttpClient's HttpException's ```StatusCodeException``` does not seem to have any way of capturing the response body. 

Thanks!

**Comment by coco98** [comment]
Ah got it!

```
let opts = defaults { redirects = 0, checkStatus = Just (\_ _ _ -> Nothing)) }
getWith opts "http://httpbin.org/status/418"
```

**Comment by andrewthad** [comment]
Thanks for figuring that out. I was struggling with the same issue.
