### ISSUE TITLE
`Postable` instance for `()`

### ISSUE THREAD

**Issue by andrewthad** [bos/wreq#67]
Could we have a `Postable` instance for `()`? I know it seems pretty trivial, but sometimes when I want to do a post request with no data, I feel like typing Text.empty feels cumbersome (and `OverloadingStrings` prevents `""` from working as I would want).

Actually, now that I think about it a little more, I feel like having a data type like this:

    data NoPostData = NoPostData

with the appropriate instance would be best. It makes the intent of the calling code more clear.

**Comment by bos** [comment]
I am reasonably happy with `Text.empty` instead, as it's clear what is happening.
