### ISSUE TITLE
Add option to emulate `curl -k` behavior

### ISSUE THREAD

**Issue by japesinator** [bos/wreq#68]
I could not find in the documentation a way of simply ignoring bad certificates, but I would like to do so

**Comment by abailly** [comment]
Here is what I do:

```
ignoreTLSCertificatesSettings :: Bool -> ManagerSettings
ignoreTLSCertificatesSettings cadisable = mkManagerSettings (TLSSettingsSimple cadisable False False) Nothing

withTlsSettings :: Options -> Bool -> Options
withTlsSettings opts cadisable = opts & manager .~ Left (ignoreTLSCertificatesSettings cadisable)

```

**Comment by bos** [comment]
Thanks, @abailly. For obvious reasons I don't want to document this :-)

**Comment by abailly** [comment]
I found it useful for automated testing purpose without going through the hassle of setting up a whole closed circuit CA stack :-)
