### ISSUE TITLE
Extend `asJSON` to accept content types with `+json`?

### ISSUE THREAD

**Issue by menelaos** [bos/wreq#69]
Would it make sense for `asJSON` to not only accept `application/json` as content type but also allow `+json` suffixed types like e.g. `application/sparql-results+json`?

**Comment by bos** [comment]
It would be doable. I don't know how widespread that convention is, though.

**Comment by kaoskorobase** [comment]
I think it's used in APIs quite often, e.g. Github's `application/vnd.github.v3+json` or `application/ld+json` in JSON-LD APIs.

**Comment by menelaos** [comment]
@ondrap Thanks!
