### ISSUE TITLE
`managerResponseTimeout` doesn't seem to have any effect

### ISSUE THREAD

**Issue by cheecheeo** [bos/wreq#70]
When I run the following code I get a response, but I expect a timeout:

``` haskell
{-# LANGUAGE OverloadedStrings #-}
import Network.HTTP.Client (ManagerSettings(..))
import qualified Network.HTTP.Client as HTTP
import qualified Network.Wreq.Session as Sess
import Control.Lens
import Network.Wreq

oneSecond :: Int
oneSecond = 1000000

httpGet mgr =
  Sess.getWith (defaults & manager .~ Right mgr)

main :: IO ()
main = do
  mgr <-
    HTTP.newManager
      (HTTP.defaultManagerSettings {
        managerResponseTimeout = Just (3 * oneSecond)
      })
  Sess.withAPISession (\session -> do
    resp <- httpGet mgr session "http://httpbin.org/delay/5"
    print resp)
```

in ghci:

```
*Main> main
Response {responseStatus = Status {statusCode = 200, statusMessage = "OK"}, responseVersion = HTTP/1.1, responseHeaders = [("Server","nginx"),("Date","Mon, 24 Aug 2015 22:23:12 GMT"),("Content-Type","application/json"),("Content-Length","253"),("Connection","keep-alive"),("Access-Control-Allow-Origin","*"),("Access-Control-Allow-Credentials","true")], responseBody = "{\n  \"args\": {}, \n  \"data\": \"\", \n  \"files\": {}, \n  \"form\": {}, \n  \"headers\": {\n    \"Accept-Encoding\": \"gzip\", \n    \"Host\": \"httpbin.org\", \n    \"User-Agent\": \"haskell wreq-0.4.0.0\"\n  }, \n  \"origin\": \"8.25.197.27\", \n  \"url\": \"http://httpbin.org/delay/5\"\n}\n", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
```

**Comment by simonmichael** [comment]
I have the same problem here (wreq 0.4.0.0): the timeout is obeyed by Network.Wreq.getWith, but ignored by  by Network.Wreq.Session.getWith.

**Comment by simonmichael** [comment]
I found that you have to set the timeout (at least) in the session options; the one in the get options is ignored. Eg:
```
let settings = defaultManagerSettings{managerResponseTimeout=Just 1000000}
S.withSessionControl Nothing settings $ \sess -> do
   S.get sess url  -- or S.getWith
```
This should be mentioned in docs, and perhaps the timeout specified in getWith options should override the session timeout.

**Comment by cheecheeo** [comment]
@simonmichael Yes, the following times out as expected:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import Network.HTTP.Client (ManagerSettings(..))
import qualified Network.HTTP.Client as HTTP
import qualified Network.Wreq.Session as Sess
import Control.Lens
import Network.Wreq

oneSecond :: Int
oneSecond = 1000000

httpGet mgr =
  Sess.getWith (defaults & manager .~ Right mgr)

main :: IO ()
main = do
  let settings =
        HTTP.defaultManagerSettings
          {managerResponseTimeout = Just (3 * oneSecond)}
  Sess.withSessionControl Nothing settings (\session -> do
    resp <- Sess.getWith defaults session "http://httpbin.org/delay/5"
    print resp)
```

```
% stack ghci wreq http-conduit           
Run from outside a project, using implicit global project config
Using resolver: lts-5.2 from implicit global project's config file: /home/jchee/.stack/global-project/stack.yaml
Configuring GHCi with the following packages: 
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Ok, modules loaded: none.
λ: :load wreq_70.hs 
[1 of 1] Compiling Main             ( wreq_70.hs, interpreted )
Ok, modules loaded: Main.
λ: main
*** Exception: ResponseTimeout
```

**Comment by atcol** [comment]
This still seems to be an issue in wreq version 0.5.1.0:

    let settings = defaultManagerSettings { managerResponseTimeout = responseTimeoutMicro 100000000 }
    W.withSessionControl Nothing settings $ \sess -> do
        S.post sess url body 

Results in `ResponseTimeoutDefault`:

    HttpExceptionRequest Request {
      host                 = "1.2.3.4"
      port                 = 8080
      secure               = False
      requestHeaders       = [("Content-Type","application/octet-stream"),("User-Agent","haskell wreq-0.5.1.0")]
      path                 = "/blah/blah"
      queryString          = ""
      method               = "POST"
      proxy                = Nothing
      rawBody              = False
      redirectCount        = 10
      responseTimeout      = ResponseTimeoutDefault
      requestVersion       = HTTP/1.1
    }
     (ConnectionFailure Network.Socket.connect: <socket: 12>: does not exist (Connection refused))

**Comment by ondrap** [comment]
The manager settings for session-oriented commands is ignored. I have added the information to the documentation. It seems to me better if it is ignored (selectively enforcing some attributes from the manager configuration doesn't seem to me like a good idea).
