### ISSUE TITLE
Expose Network.HTTP.Client.HistoriedResponse

### ISSUE THREAD

**Issue by domenkozar** [bos/wreq#71]
I'd wreq to follow redirects, as I'm not interested into response body but the final URL. Currently `wreq` doesn't expose `Network.HTTP.Client.HistoriedResponse` in Response type.

**Comment by domenkozar** [comment]
@bos is this something you'd like to be supported?

**Comment by domenkozar** [comment]
Meanwhile I've found a workaround. I can do a `head` request that will return a 302 and fail, but parsing the Location header I can get the final URL.

**Comment by afcady** [comment]
I also implemented a rather ugly hack to accomplish this a while back:

https://github.com/bos/wreq/compare/master...afcady:master
