### ISSUE TITLE
Misleading FailedConnectionException

### ISSUE THREAD

**Issue by jcelliott** [bos/wreq#75]
While using [aura](https://github.com/aurapm/aura), I ran into aurapm/aura#348. It seems that the error is coming from wreq, but I don't know that for sure.

wreq is reporting a FailedConnectionException when the problem is actually insufficient entropy in the system pool, which is rather difficult to debug. Could we get a more specific error message for that case?

**Comment by bos** [comment]
You'll need to go deeper in the stack to find the source of this problem. `wreq` knows nothing about random data, and is simply passing along whatever error one of its dependencies produces. I assume that the problem originates somewhere in a dependency of `http-client-tls`.

**Comment by erlandsona** [comment]
So how do I fix this again... Sorry I'm running into the same issue and unfortunately I'm not a CS guy so fixing entropy makes a bit less sense to me? The weird thing is that pacman still works. But if I try to ping aur.archlinux.org it gives me the same error?
