### ISSUE TITLE
It shall be reasonable to add a standalone `newSession` action

### ISSUE THREAD

**Issue by TerrorJack** [bos/wreq#81]
Currently, the only way to use a `Session` is using the `with`-style functions in `Network.Wreq.Session`. A standalone `newSession` is not provided, which can be troublesome when one wants to use `wreq` to implement some web service's binding library and wants to embed the `wreq`'s `Session` into the new library's `Session` and allow users to use `Session` in a natural way: first initiate one, then pass it around, no need to force everything in a big ugly do-block and pass to a `withSession`.

And although the documentation says "The Session will no longer be valid after that function returns.", this is actually not the case! The implementation of `withSession` tracks down to `withManager` in `http-client`, which is **deprecated** and doesn't do any clean-up work. It is tested that `newSession = withSession pure` works, the returned `Session` works as long as it's still in scope and not garbage collected.

**Comment by jfischoff** [comment]
👍
