### ISSUE TITLE
TlsExceptionHostPort (HandshakeFailed Error_EOF) "chrome.google.com" 443

### ISSUE THREAD

**Issue by tejon** [bos/wreq#88]
Not the greatest issue title but I can't think of a more concise summary! This is happening with any request I make to chrome.google.com, and nowhere else (that I've found -- notably working sites include Steam, Amazon, iTunes). It occurs with both `tlsManagerSettings` and a constructed manager with `TLSSettings True False False`, and also with regular HTTP on port 80. It's possible this is some sort of deliberate rejection, but EOF during the handshake isn't the usual signal for that and I've dug about as far as my "expertise" reliably allows. Figured I should pass it upstream for review, at least.

The application is a product data scraper service, public source available here: https://github.com/tejon/Meeseeks

**Comment by erdeszt** [comment]
I'm having a similar issue, one of my application that was running fine before failed after a new build/deploy today with this message:
`TlsExceptionHostPort (HandshakeFailed (Error_Protocol ("certificate rejected: [SelfSigned]",True,CertificateUnknown))) "api.enterprise.apigee.com" 443`
But if I open `https://api.enterprise.apigee.com` in chrome I get the green lock icon indicating that the connection is secure. I can provide code or can try the tls settings mentioned by @tejon if necessary.

**Comment by isamert** [comment]
I'm also getting this exact same error on _google_ related pages which even includes `google.com`. More interestingly, I don't get this error on `m.google.com`.

**Comment by sgronblo** [comment]
I get this same error when trying to access calendar.google.com. Curl does not complain about the same URL.

**Comment by filterfish** [comment]
This was a problem in [hs-tls](https://github.com/vincenthz/hs-tls). See here: https://github.com/vincenthz/hs-tls/issues/152

You should just be able to use tls-1.3.9 it in stackage lts-7.16 and nightles of course. It worked for me.

**Comment by ondrap** [comment]
Not a wreq problem, closing.
