### ISSUE TITLE
TlsNotSupported on Https requests via proxy

### ISSUE THREAD

**Issue by o1lo01ol1o** [bos/wreq#90]
I thought this was an issue with http-client-tls but it [appears](https://github.com/snoyberg/http-client/issues/234) not to be.  

Using the following syntax with wreq fails:

```
let opts = defaults & proxy ?~ httpProxy ip port
                  -- unsecured https proxies fail as well
                  -- & header hProxyAuthorization .~ [(encode $ pack "usr:pass")]
                  & manager .~ Left (defaultManagerSettings { managerResponseTimeout = Just (100000 * 30) } )

  r <- getWith opts url
```

**Comment by markus1189** [comment]
Just had the same problem without a proxy, you have to use `tlsManagerSettings` from `Network.HTTP.Client.TLS` instead of `defaultManagerSettings`

**Comment by ondrap** [comment]
Yes, that seems to be the correct solution.
