### ISSUE TITLE
Wreq status

### ISSUE THREAD

**Issue by Rydgel** [bos/wreq#93]
Is this project still supported?
If not, what lib do you recommend using instead?

**Comment by mrkkrp** [comment]
I'm not the author of Wreq, but anyway:

* https://github.com/snoyberg/http-client — for tried-and-true stuff everyone uses.
* https://github.com/mrkkrp/req — haven't announced this one yet, just FYI.

**Comment by Rydgel** [comment]
@mrkkrp thank you

**Comment by noraesae** [comment]
I really like how wreq works and hope the project continues. To contributors, if there is anything I can help, please let me know.
